[project]
name = "keyword-categorizer"
version = "0.1.0"
description = "AI-powered keyword categorization by country/language"
requires-python = ">=3.8"
dependencies = [
    "pandas>=2.0.0",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
]

[tool.uv]
dev-dependencies = [] 